version: '3.9'

services:

    db:
        build:
            context: ./db
        container_name: event-db
        image: event-db
        networks:
            - event
        command: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data:delegated
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_PASSWORD=password

networks:
    event:
        name: event
        
volumes:
    postgres-data: